project:
  type: website
  resources:
    - "feed.xml"
    - "googleaac10e261f67700b.html"

website:
  title: "A Chemical Engineer's Notebook"
  site-url: https://aefarrell.github.io
  description: "A collection of notebooks about chemical engineering and analysis"
  open-graph: true
  navbar:
    left:
      - icon: info-circle
        href: "about.qmd"
        text: "about"
      - icon: wrench-adjustable-circle
        href: "projects.qmd"
        text: "projects"
      - icon: archive
        href: "archive.qmd"
        text: "posts"
    right:
      - icon: rss
        href: "index.xml"
      - icon: github
        href: "https://github.com/aefarrell/aefarrell.github.io/"
  repo-url: https://github.com/aefarrell/aefarrell.github.io
  repo-actions: [source, issue]
  page-footer:
    center: "© 2025 Allan Farrell [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) <br /> Made with [Quarto](https://quarto.org)"

format:
  html:
    respect-user-color-scheme: false
    theme:
      light: united
      dark: superhero
    css: styles.css



