project:
  type: website

website:
  title: "A Chemical Engineer's Notebook"
  site-url: https://aefarrell.github.io
  description: "A collection of notebooks about chemical engineering and analysis"
  open-graph: true
  navbar:
    left:
      - icon: info-circle
        href: "about.qmd"
        text: "about"
      - icon: wrench-adjustable-circle
        href: "projects.qmd"
        text: "projects"
    right:
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      - pulse
      - brand
    css: styles.css



