project:
  type: website
  resources:
    - "feed.xml"

website:
  title: "A Chemical Engineer's Notebook"
  site-url: https://aefarrell.github.io
  description: "A collection of notebooks about chemical engineering and analysis"
  open-graph: true
  navbar:
    left:
      - icon: info-circle
        href: "about.qmd"
        text: "about"
      - icon: wrench-adjustable-circle
        href: "projects.qmd"
        text: "projects"
      - icon: archive
        href: "archive.qmd"
        text: "posts"
    right:
      - icon: rss
        href: "index.xml"
      - icon: github
        href: "https://github.com/aefarrell/aefarrell.github.io/"
format:
  html:
    theme:
      - pulse
      - brand
    css: styles.css



